// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...\n/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0zQf5EFr370ZRnaZG9cc0Np0eYMrcVpY',
    appId: '1:307586883658:web:c527bdf3331add1eeec6b3',
    messagingSenderId: '307586883658',
    projectId: 'tasting-cli-59e68',
    authDomain: 'tasting-cli-59e68.firebaseapp.com',
    storageBucket: 'tasting-cli-59e68.firebasestorage.app',
    measurementId: 'G-KJ6EHP7GZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoYlYEdAM1qMeuBlydF4uCmjrIPMHoG3k',
    appId: '1:307586883658:android:d407cc8b9fab0f5deec6b3',
    messagingSenderId: '307586883658',
    projectId: 'tasting-cli-59e68',
    storageBucket: 'tasting-cli-59e68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCazNHU0elowDN2GaOWJbKbCMDYVscLF4M',
    appId: '1:307586883658:ios:a095f692077e2254eec6b3',
    messagingSenderId: '307586883658',
    projectId: 'tasting-cli-59e68',
    storageBucket: 'tasting-cli-59e68.firebasestorage.app',
    iosBundleId: 'com.example.firstProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCazNHU0elowDN2GaOWJbKbCMDYVscLF4M',
    appId: '1:307586883658:ios:a095f692077e2254eec6b3',
    messagingSenderId: '307586883658',
    projectId: 'tasting-cli-59e68',
    storageBucket: 'tasting-cli-59e68.firebasestorage.app',
    iosBundleId: 'com.example.firstProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0zQf5EFr370ZRnaZG9cc0Np0eYMrcVpY',
    appId: '1:307586883658:web:d90b42377913fe15eec6b3',
    messagingSenderId: '307586883658',
    projectId: 'tasting-cli-59e68',
    authDomain: 'tasting-cli-59e68.firebaseapp.com',
    storageBucket: 'tasting-cli-59e68.firebasestorage.app',
    measurementId: 'G-6HKCVSCNMQ',
  );
}